version: '3.3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion      
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  ncdb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=p4ssw0rd
    command: --innodb-read-only-compressed=OFF      
    volumes:
      - ncdb-data:/var/lib/mysql

  nc:
    image: nextcloud:22.0-apache
    restart: always
    depends_on:
      - ncdb
    volumes:
      - nc-nextcloud:/var/www/html
      - nc-apps:/var/www/html/custom_apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_HOST=ncdb
      - VIRTUAL_HOST=next.tudominio.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=next.tudominio.com
      - LETSENCRYPT_EMAIL=info@tudominio.com
      - RESOLVE_TO_PROXY_IP=true
          
  office:
    image: collabora/code:6.4.10.5
    restart: always
    environment:
      - "domain=next\\.tudominio\\.com"
      - "username=admin"
      - "password="
      - "SLEEPFORDEBUGGER=0"
      - VIRTUAL_HOST=office.tudominio.com
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=office.tudominio.com
      - LETSENCRYPT_EMAIL=info@tudominio.com
      - RESOLVE_TO_PROXY_IP=true
      - NETWORK_ACCESS=internal
    expose:
      - 9980
    cap_add:
      - MKNOD
          
volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost:
  ncdb-data:
  nc-nextcloud:
  nc-apps:
  nc-config:
  nc-data:
